-- =============================================================================
-- Blissim - Test technique Dev Backend
-- Schéma e-commerce : clients, produits, commandes, lignes de commande
-- + commentaires sur les produits, gérés par l'application catalogue (partie PHP)
-- Cible : PostgreSQL 12+
--
-- Le catalogue est celui de fakestoreapi.com : la table `product` en est la copie
-- locale (alimentée par la commande `bin/console app:import-products`).
-- Un produit a son propre id (celui de l'application) et, s'il provient d'une source
-- externe, le nom de cette source et l'id du produit chez ce fournisseur.
--
-- Toutes les tables ont deux colonnes techniques gérées par la base, jamais par l'application :
--   created_at : date de création de la ligne (DEFAULT CURRENT_TIMESTAMP)
--   updated_at : date de dernière modification (trigger set_updated_at), égale
--                à created_at tant que la ligne n'a pas été modifiée
--
-- Le script s'exécute dans la base courante (psql -d blissim) : il ne crée pas la base.
-- Rejouer ce script réinitialise entièrement les tables, commentaires compris.
-- =============================================================================

SET client_encoding = 'UTF8';

DROP TABLE IF EXISTS comment, order_item, customer_order, product, customer;

-- -----------------------------------------------------------------------------
-- updated_at : PostgreSQL n'a pas d'équivalent à ON UPDATE CURRENT_TIMESTAMP.
-- Ce trigger met la date à jour seulement si une valeur de la ligne change (un
-- upsert avec des données identiques ne la modifie pas), sauf si la requête
-- fournit elle-même une nouvelle valeur de updated_at.
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
    IF NEW IS DISTINCT FROM OLD AND NEW.updated_at IS NOT DISTINCT FROM OLD.updated_at THEN
        NEW.updated_at := CURRENT_TIMESTAMP;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- -----------------------------------------------------------------------------
-- Clients
-- -----------------------------------------------------------------------------
CREATE TABLE customer (
    id          INTEGER      GENERATED BY DEFAULT AS IDENTITY,
    first_name  VARCHAR(100) NOT NULL,
    last_name   VARCHAR(100) NOT NULL,
    email       VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uq_customer_email UNIQUE (email)
);

CREATE TRIGGER trg_customer_updated_at BEFORE UPDATE ON customer
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- -----------------------------------------------------------------------------
-- Produits (copie locale du catalogue FakeStore)
-- id                  : identifiant de l'application, référencé par les clés étrangères.
-- source              : origine du produit ('fakestore'), NULL pour un produit créé dans l'application.
-- supplier_product_id : identifiant du produit chez la source. VARCHAR, car une autre
--                       source peut utiliser un SKU ou un UUID. Unique par source : c'est
--                       la clé de l'upsert à l'import. Renseigné si et seulement si source l'est.
-- Les montants sont stockés en centimes (entiers) : calculs exacts, sans erreur
-- d'arrondi, et un type simple à manipuler côté PHP (int). 109,95 € => 10995.
-- `price_cents` est le prix catalogue courant : il peut changer à chaque import,
-- c'est pour ça qu'il est recopié dans order_item au moment de l'achat.
-- -----------------------------------------------------------------------------
CREATE TABLE product (
    id                   INTEGER       GENERATED BY DEFAULT AS IDENTITY,
    source               VARCHAR(50)   NULL,
    supplier_product_id  VARCHAR(64)   NULL,
    name                 VARCHAR(255)  NOT NULL,
    description          TEXT          NULL,
    category             VARCHAR(100)  NOT NULL DEFAULT '',
    image_url            VARCHAR(500)  NOT NULL,
    price_cents          INTEGER       NOT NULL,
    created_at           TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMP(0)  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT uq_product_supplier UNIQUE (source, supplier_product_id),
    CONSTRAINT chk_product_supplier CHECK ((source IS NULL) = (supplier_product_id IS NULL)),
    CONSTRAINT chk_product_price CHECK (price_cents >= 0)
);

CREATE INDEX idx_product_category ON product (category);

CREATE TRIGGER trg_product_updated_at BEFORE UPDATE ON product
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- -----------------------------------------------------------------------------
-- Commandes
-- Table nommée customer_order car ORDER est un mot réservé SQL.
-- ON DELETE RESTRICT : on ne supprime pas un client qui a un historique d'achat.
-- ordered_at est la date métier de la commande (celle des requêtes), distincte de
-- created_at, date technique d'insertion de la ligne (ex. commande importée plus tard).
-- -----------------------------------------------------------------------------
CREATE TABLE customer_order (
    id           INTEGER      GENERATED BY DEFAULT AS IDENTITY,
    customer_id  INTEGER      NOT NULL,
    status       VARCHAR(20)  NOT NULL DEFAULT 'pending',
    ordered_at   TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at   TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at   TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_order_customer FOREIGN KEY (customer_id)
        REFERENCES customer (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT chk_order_status CHECK (status IN ('pending', 'paid', 'shipped', 'cancelled'))
);

-- PostgreSQL n'indexe pas automatiquement les clés étrangères
CREATE INDEX idx_order_customer ON customer_order (customer_id);

-- Sert la requête 2 (ventes des 7 derniers jours)
CREATE INDEX idx_order_ordered_at ON customer_order (ordered_at);

CREATE TRIGGER trg_customer_order_updated_at BEFORE UPDATE ON customer_order
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- -----------------------------------------------------------------------------
-- Lignes de commande
-- unit_price_cents = prix payé au moment de l'achat, en centimes
-- (figé, indépendant de product.price_cents).
-- Un même produit n'apparaît qu'une fois par commande (on cumule la quantité).
-- -----------------------------------------------------------------------------
CREATE TABLE order_item (
    id                INTEGER      GENERATED BY DEFAULT AS IDENTITY,
    order_id          INTEGER      NOT NULL,
    product_id        INTEGER      NOT NULL,
    quantity          SMALLINT     NOT NULL,
    unit_price_cents  INTEGER      NOT NULL,
    created_at        TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_item_order FOREIGN KEY (order_id)
        REFERENCES customer_order (id) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_item_product FOREIGN KEY (product_id)
        REFERENCES product (id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT uq_item_order_product UNIQUE (order_id, product_id),
    CONSTRAINT chk_item_quantity CHECK (quantity > 0),
    CONSTRAINT chk_item_price CHECK (unit_price_cents >= 0)
);

-- order_id est déjà couvert par uq_item_order_product (première colonne)
CREATE INDEX idx_item_product ON order_item (product_id);

CREATE TRIGGER trg_order_item_updated_at BEFORE UPDATE ON order_item
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- -----------------------------------------------------------------------------
-- Commentaires sur les produits (application catalogue)
-- ON DELETE CASCADE : un commentaire n'a pas de sens sans son produit.
-- -----------------------------------------------------------------------------
CREATE TABLE comment (
    id          INTEGER      GENERATED BY DEFAULT AS IDENTITY,
    product_id  INTEGER      NOT NULL,
    author      VARCHAR(100) NOT NULL,
    content     TEXT         NOT NULL,
    created_at  TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    CONSTRAINT fk_comment_product FOREIGN KEY (product_id)
        REFERENCES product (id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE INDEX idx_comment_product ON comment (product_id);

CREATE TRIGGER trg_comment_updated_at BEFORE UPDATE ON comment
    FOR EACH ROW EXECUTE FUNCTION set_updated_at();


-- =============================================================================
-- Jeu de données de test
-- Les dates sont relatives à NOW() pour que la requête "7 derniers jours"
-- donne toujours le même résultat, quel que soit le jour où le script est joué.
-- =============================================================================

INSERT INTO customer (id, first_name, last_name, email) VALUES
    (1, 'Camille', 'Martin',  'camille.martin@example.com'),
    (2, 'Lucas',   'Bernard', 'lucas.bernard@example.com'),
    (3, 'Léa',     'Dubois',  'lea.dubois@example.com'),
    (4, 'Hugo',    'Thomas',  'hugo.thomas@example.com'),
    (5, 'Chloé',   'Robert',  'chloe.robert@example.com'),
    (6, 'Nathan',  'Petit',   'nathan.petit@example.com');

-- Extrait du catalogue FakeStore : l'import complètera et mettra à jour ces lignes
-- (reconnues par source + supplier_product_id). Le dernier produit est propre à l'application.
INSERT INTO product (id, source, supplier_product_id, name, description, category, image_url, price_cents) VALUES
    (1, 'fakestore', '1', 'Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops', 'Your perfect pack for everyday use and walks in the forest.',
        'men''s clothing', 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_t.png', 10995),
    (2, 'fakestore', '2', 'Mens Casual Premium Slim Fit T-Shirts', 'Slim-fitting style, contrast raglan long sleeve, three-button henley placket.',
        'men''s clothing', 'https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_t.png', 2230),
    (3, 'fakestore', '3', 'Mens Cotton Jacket', 'Great outerwear jackets for Spring/Autumn/Winter.',
        'men''s clothing', 'https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_t.png', 5599),
    (4, 'fakestore', '4', 'Mens Casual Slim Fit', 'The color could be slightly different between on the screen and in practice.',
        'men''s clothing', 'https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_t.png', 1599),
    (5, 'fakestore', '5', 'John Hardy Women''s Legends Naga Gold & Silver Dragon Station Chain Bracelet', 'From our Legends Collection, the Naga was inspired by the mythical water dragon.',
        'jewelery', 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_t.png', 69500),
    -- jamais vendu
    (6, 'fakestore', '6', 'Solid Gold Petite Micropave', 'Satisfaction Guaranteed. Return or exchange any order within 30 days.',
        'jewelery', 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_t.png', 16800),
    -- produit créé dans l'application, sans source externe (jamais vendu)
    (7, NULL, NULL, 'Coffret découverte Blissim', 'Une sélection de cinq produits beauté.',
        'beauty', 'https://example.com/img/coffret-decouverte.png', 1490);

INSERT INTO customer_order (id, customer_id, status, ordered_at) VALUES
    -- commandes anciennes (hors fenêtre de 7 jours)
    (1, 1, 'shipped',   NOW() - INTERVAL '30 days'),
    (2, 2, 'shipped',   NOW() - INTERVAL '15 days'),
    -- commandes récentes
    (3, 3, 'paid',      NOW() - INTERVAL '6 days'),
    (4, 1, 'paid',      NOW() - INTERVAL '3 days'),
    (5, 4, 'pending',   NOW() - INTERVAL '1 day'),
    (6, 5, 'shipped',   NOW() - INTERVAL '2 hours'),
    -- commande annulée récente : ne doit pas compter dans les ventes
    (7, 6, 'cancelled', NOW() - INTERVAL '2 days');

-- Le sac à dos (produit 1) est passé de 99,95 € à 109,95 € : les anciennes lignes gardent l'ancien prix.
INSERT INTO order_item (order_id, product_id, quantity, unit_price_cents) VALUES
    (1, 1, 1,  9995),
    (1, 4, 2,  1599),
    (2, 2, 1,  2230),
    (2, 1, 2,  9995),
    (3, 3, 2,  5599),
    (3, 5, 1, 69500),
    (4, 1, 1, 10995),
    (4, 3, 1,  5599),
    (5, 4, 3,  1599),
    (5, 2, 1,  2230),
    (6, 1, 2, 10995),
    (6, 4, 1,  1599),
    (7, 5, 4, 69500),
    (7, 1, 1, 10995);

-- Les id ont été fournis explicitement : les séquences doivent repartir après le plus grand,
-- sinon la prochaine insertion sans id entrerait en conflit avec la ligne 1.
SELECT setval(pg_get_serial_sequence('customer', 'id'), (SELECT MAX(id) FROM customer));
SELECT setval(pg_get_serial_sequence('product', 'id'), (SELECT MAX(id) FROM product));
SELECT setval(pg_get_serial_sequence('customer_order', 'id'), (SELECT MAX(id) FROM customer_order));


-- =============================================================================
-- Requêtes demandées
-- =============================================================================

-- 1. Prénom et nom des clients ayant commandé le produit product_id = 1.
--    DISTINCT : un client qui a commandé le produit plusieurs fois n'apparaît qu'une fois.
--    Résultat attendu sur le seed : Camille Martin, Lucas Bernard, Chloé Robert, Nathan Petit.
--    (On ne filtre pas sur le statut : la question porte sur "avoir commandé".)
SELECT DISTINCT c.first_name, c.last_name
FROM customer c
JOIN customer_order o ON o.customer_id = c.id
JOIN order_item oi    ON oi.order_id   = o.id
WHERE oi.product_id = 1
ORDER BY c.last_name, c.first_name;

-- 2. Produits vendus au cours des 7 derniers jours, avec leur nom et la quantité
--    totale vendue, triés par quantité décroissante.
--    Les commandes annulées ne sont pas des ventes : elles sont exclues.
--    La condition sur ordered_at est "sargable" et profite de idx_order_ordered_at.
--    Résultat attendu sur le seed :
--      Mens Casual Slim Fit 4 / Fjallraven Backpack 3 / Mens Cotton Jacket 3 /
--      John Hardy Bracelet 1 / Mens Casual Premium T-Shirts 1
SELECT p.id, p.name, SUM(oi.quantity) AS total_quantity
FROM order_item oi
JOIN customer_order o ON o.id = oi.order_id
JOIN product p        ON p.id = oi.product_id
WHERE o.ordered_at >= NOW() - INTERVAL '7 days'
  AND o.status <> 'cancelled'
GROUP BY p.id, p.name
ORDER BY total_quantity DESC, p.name;
